services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: urlshortener
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    env_file:
      - .env.production
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SERVICE_URL=${SERVICE_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: urlshortener-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - app
    env_file:
      - .env.production
    environment:
      - VITE_API_URL=${VITE_API_URL}