services:
  mongodb:
    image: mongo:6.0.20
    container_name: mongodb
    ports:
      - "27017:27017"
    command: --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: urlshortener
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
