services:
  urlshortener-backend:
    image: melihemreguler/urlshortener-backend:latest
    container_name: urlshortener
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DATABASE=${MONGODB_DATABASE:-urlshortenerdb}
      - SERVICE_URL=${SERVICE_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - VIRTUAL_HOST=urlshortener.melihemre.dev
      - VIRTUAL_PATH=/api
      - VIRTUAL_PORT=8080
    networks:
      - web
  frontend:
    image: melihemreguler/urlshortener-frontend:latest
    container_name: urlshortener-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - urlshortener-backend
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VIRTUAL_HOST=urlshortener.melihemre.dev
      - LETSENCRYPT_HOST=urlshortener.melihemre.dev
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-guler@melihemre.dev}
    networks:
      - web

networks:
  web:
    external: true