spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:secret@localhost:27017/urlshortenerdb?authSource=admin}
      database: ${MONGODB_DATABASE:urlshortenerdb}
  web:
    resources:
      add-mappings: false
  profiles:
    active: production
server:
  port: 8080
  error:
    include-stacktrace: never
    include-exception: false
    include-message: never
    include-binding-errors: never
    whitelabel:
      enabled: false
logging:
  level:
    root: INFO
    com.github.melihemreguler: DEBUG
springdoc:
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
service:
  config:
    serviceUrl: ${SERVICE_URL:http://localhost:8080}
cors:
  allowed:
    origins:
      - "http://localhost:3000"
      - "http://localhost:5173"
      - "http://urlshortener-frontend:3000"
      - "https://urlshortener.melihemre.dev"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    headers:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    credentials: true
    max-age: 3600

newrelic:
  config:
    license_key: ${NEW_RELIC_LICENSE_KEY:}
    app_name: URLShortener Backend
    log_file_name: newrelic_agent.log
    audit_mode: false
    log_level: info
    enable_auto_app_naming: false
    enable_auto_transaction_naming: true
    labels:
      environment: ${SPRING_PROFILES_ACTIVE:development}
      team: melihemre
      service: urlshortener-backend