spring:
  data:
    mongodb:
      uri: "mongodb://admin:secret@localhost:27017/urlshortenerdb?authSource=admin"
server:
  port: 8080
logging:
  level:
    root: INFO
    com.github.melihemreguler: DEBUG
springdoc:
  swagger-ui:
    url: "/v3/api-docs"
service:
  config:
    serviceUrl: "http://localhost:8080"